// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW97f3pJkdJHG9cTy9yTGvd7nAWTm2Wss',
    appId: '1:686803358585:web:969c75800d7961a1ebd5a8',
    messagingSenderId: '686803358585',
    projectId: 'cholay-ice-sale',
    authDomain: 'cholay-ice-sale.firebaseapp.com',
    storageBucket: 'cholay-ice-sale.appspot.com',
    measurementId: 'G-MLV130LY3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmE_zqCDU_LPQKn6sPHmF6AaWip_aAkGA',
    appId: '1:686803358585:android:fa64cdc476e2fa2debd5a8',
    messagingSenderId: '686803358585',
    projectId: 'cholay-ice-sale',
    storageBucket: 'cholay-ice-sale.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqjOiO11a4ZK1fxdDOPrA8o6CoTe8I3ck',
    appId: '1:686803358585:ios:c3b54280e1855340ebd5a8',
    messagingSenderId: '686803358585',
    projectId: 'cholay-ice-sale',
    storageBucket: 'cholay-ice-sale.appspot.com',
    iosBundleId: 'com.example.cholayIceSale',
  );
}
